trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'

jobs:
- job: Build
  pool:
    name: Docker
    # vmImage: Windows-2019
  # Use maximum timeout, ie. 6 hours 
  timeoutInMinutes: 0

  steps:
  - powershell: |
      $password = ConvertTo-SecureString -String $env:storageAccountKey -AsPlainText -Force;
      $credential = New-Object System.Management.Automation.PSCredential -ArgumentList "AZURE\$($env:storageAccountName)", $password;
      New-PSDrive -Name Z -PSProvider FileSystem -Root "$env:storageAccountLocation" -Credential $credential -Persist;
    env:
      storageAccountKey: $(storageAccountKey)
      storageAccountName: $(storageAccountName)
      storageAccountLocation: $(storageAccountLocation)
    displayName: Mount Files

  - task: CopyFiles@2
    inputs:
      sourceFolder: Z:/ 
      targetFolder: files
      cleanTargetFolder: true

  - task: CopyFiles@2
    displayName: Copy XC license
    inputs:
      sourceFolder: Z:/
      targetFolder: xc/license/
      contents: license.xml
      cleanTargetFolder: true

  - task: CopyFiles@2
    displayName: Copy XP license
    inputs:
      sourceFolder: Z:/
      targetFolder: xp/license/
      contents: license.xml
      cleanTargetFolder: true

  - powershell: | 
      If (Test-Path ./files/*.pfx) { Write-Host "Re-using found certificates"; ls ./files/*.pfx } Else { ./Generate-Certificates.ps1 }
    displayName: Generate certificates

  - task: PowerShell@2
    displayName: Build images
    inputs:
      targetType: 'filePath'
      filePath: build.ps1
      arguments: > 
          All

  - script: docker login -u $(dockerId) -p $(dockerPwd) "$(dockerId).azurecr.io"
    displayName: Docker login

  - task: PowerShell@2
    displayName: (Optionally) Push images
    inputs:
      targetType: 'filePath'
      filePath: build.ps1
      arguments: > 
          PushXp
          PushXc
          --RepoImagePrefix $(dockerId)

  - powershell: Remove-PSDrive -Name Z
    displayName: Unmount Files

  # - script: docker system prune -f -a
